spring:
  datasource:
    url: jdbc:postgres://postgres:5432/cineradar_prod
    username: cineradar
    password: password1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis
      port: 6379
      database: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true